### ISSUE TITLE
不能正常格式化less

### ISSUE THREAD

**Issue by gucong3000** [mutian/Sublime-CSS-Format#32]
```LESS
.btn-linear-gradient(@startColor:#555, @endColor:#333) {
	filter: e(%("progid:DXImageTransform.Microsoft.Gradient(StartColorStr='%d', EndColorStr='%d')", argb(@startColor), argb(@endColor)));
	background: linear-gradient(to bottom, @startColor, @endColor);
}
```
按“expand-bs”方式格式化，出错。期望括号内部分不换行

**Comment by gucong3000** [comment]
```LESS
// 字体加载
.font_face(@fontname, @url: "/css/fonts"){
	font-family: @fontname;
	-webkit-font-smoothing: antialiased;
	-webkit-text-stroke-width: 0.2px;
	@font-face {
		font-family: @fontname;
		src: url("@{url}/@{fontname}.eot");
		src: url("@{url}/@{fontname}.eot?#iefix") format("embedded-opentype"), url("@{url}/@{fontname}.woff") format("woff"), url("@{url}/@{fontname}.ttf") format("truetype"), url("@{url}/@{fontname}.svg#iconfont") format("svg");
	}
}

// “分享到”功能相关图标
// 微博&#xe600;
// 微信&#xe601;
// 人人&#xe602;
// 信封&#xe603;
// Facebook&#xe604;
// QQ空间&#xe605;
.icon-shareto(@color: #000, @bgColor: #fff){
	.font_face("shareto");
	background-color: @bgColor;
	border-radius: 99em;
	line-height: 110px;
	font-weight: normal;
	font-style: normal;
	font-size: 80px;
	display: block;
	color: @color;
	height: 110px;
	width: 110px;
}
```
