### ISSUE TITLE
sass\less中，多行注释中的代码被格式化

### ISSUE THREAD

**Issue by gucong3000** [mutian/Sublime-CSS-Format#37]
```LESS
/*
.pagelink {
	text-align: center;
	position: relative;
	margin: 30px auto;		
}
*/
```
注释掉的less或sass代码，每次格式化，缩进都增加，格式化的次数越多，缩进越多
