### ISSUE TITLE
not support for #{} of sass

### ISSUE THREAD

**Issue by hahnzhu** [mutian/Sublime-CSS-Format#39]
```sass
@for $i from 1 to 7{
   .life#{$i}{
    z-index: 10 - $i;
    @include img-decoration-life(life#{$i});
    background-image:none;
   }
  }
```

output:
```sass
@for $i from 1 to 7 {
        .life# {
            $i
        }
        {
            z-index: 10 - $i;

            @include img-decoration-life(life# {
                $i
            }
            );
            background-image: none;
        }
    }
```

**Comment by cjke** [comment]
+1

**Comment by Demnogonis** [comment]
+1

The same happens in LESS

``` LESS
.hq-loop(@n, @i: 1) when (@i =< @n) {
    .col-hq-@{i}:extend(.col-hq-1) {}
    .col-hq-@{i} {
        width: (@i * 100% / @n);
    }
    .hq-loop(@n, (@i + 1));
}
.hq-loop(12);
```

is formatted to:

``` LESS
.hq-loop(@n, @i:1) when (@i =< @n) {
    .col-hq-@ {
        i
    }

    :extend(.col-hq-1) {
    }

    .col-hq-@ {
        i
    }

    {
        width: (@i * 100% / @n);
    }

    .hq-loop(@n, (@i + 1));
}

.hq-loop(12);
```
