### ISSUE TITLE
problem with filter attribute

### ISSUE THREAD

**Issue by nujabes** [mutian/Sublime-CSS-Format#42]
Thanks for such nice plugin.
I found some stange words appearing after format css. and I figured out.

```css
#googlemap .gm-style{filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter'); -webkit-filter: grayscale(100%); filter: grayscale(100%); }
	.remodal1{content:"";display: block; clear: both;}
	.remodal2{content:"";display: block; clear: both;}
	.remodal3{content:"";display: block; clear: both;}	
	.remodal4{content:"";display: block; clear: both;}
	.remodal5{content:"";display: block; clear: both;}
```
When I format css including filter attribute. The words in the url goes to the content attribute. 
like this. 
```css
#googlemap .gm-style { filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns=!string!><filter id=!string!><feColorMatrix type=!string!color-interpolation-filters=!string!values=!string!/></filter></svg>#filter'); -webkit-filter: grayscale(100%); filter: grayscale(100%); }
.remodal1 { content: "http://www.w3.org/2000/svg"; display: block; clear: both; }
.remodal2 { content: "filter"; display: block; clear: both; }
.remodal3 { content: "matrix"; display: block; clear: both; }
.remodal4 { content: "sRGB"; display: block; clear: both; }
.remodal5 { content: "0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0"; display: block; clear: both; }
```
I think it should be fixed. thanks.
