### ISSUE TITLE
Extra linebreak on Nested SCSS when using Expanded Break Selector

### ISSUE THREAD

**Issue by htc001120** [mutian/Sublime-CSS-Format#44]
```css
a {
    img {
        position: absolute;
        top: 0px;
        left: 0px;
        cursor: pointer;
    }

    &:hover {
        img {
            top: -13px;
        }

    }

}
```
