### ISSUE TITLE
Breaking code when comments share a line with uncommented code

### ISSUE THREAD

**Issue by elliottregan** [mutian/Sublime-CSS-Format#47]
### Example:
Starting with:

```css
.card { // IE Hacks. Hiding left/right arrows since IE8-10 don't handle backface-visibility very well :(
  .front, .back { overflow-x: hidden; }
}
```

when formatted to **'Compact'**:
```css
.card { // IE Hacks. Hiding left/right arrows since IE8-10 don't handle backface-visibility very well:(.front, .back { overflow-x: hidden; }
}
```

and then back to **'Expanded'**:
```
.card {
  // IE Hacks. Hiding left/right arrows since IE8-10 don't handle backface-visibility very well:(.front, .back {
    overflow-x: hidden;
  }
}
```
