### ISSUE TITLE
Breaking Selectors containing ";"

### ISSUE THREAD

**Issue by maxfragg** [mutian/Sublime-CSS-Format#48]
```CSS
#header-wrap[style*="left:0px;

"] span[widgetid=collapse_feeds_btn]>span:before {
	display: inline-block;
}
```

should be:

```CSS
#header-wrap[style*="left:0px;"] span[widgetid=collapse_feeds_btn]>span:before {
	display: inline-block;
}
```

this actually breaks the css-file at least for blink-browsers when formating expanded

(Example taken from [clean greader](https://github.com/naeramarth7/clean-greader))
